version: '3.8'

services:
  db:
    image: mysql:8
    container_name: ecommerce-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: online_shopping
    # ports:
    #   - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./Backend/online-shopping
    container_name: ecommerce-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/online_shopping?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.MySQL8Dialect
      DISK_UPLOAD_BASEPATH: /app/images
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - images:/app/images

  frontend:
    build: ./Frontend/online-shopping
    container_name: ecommerce-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db_data:
  images: